-  Вивід данних
-  Ввід данних
-  Перетворення типу
-  Оператори (математичні, логічні)
-  побудова алгоритмів


// let cost;
// const subscription = 'premium';

// switch () {
//   case 'free':
//   
//     break;

//   case 'pro':
//     cost = 100;
//     break;

//   case 'premium':
//     cost = 500;
//     break;

//   default:
//     console.log('Invalid subscription type');
// }

// console.log(cost); // 500